extends LampPanel
class_name AdderPanel

func _ready():
	_elements.append($lamp_00)
	_elements.append($lamp_01)
	_elements.append($lamp_02)
	_elements.append($lamp_03)
	_elements.append($lamp_04)
	_elements.append($lamp_05)
	_elements.append($lamp_06)
	_elements.append($lamp_07)
	_elements.append($lamp_08)
	_elements.append($lamp_09)
	_elements.append($lamp_10)
	_elements.append($lamp_11)
	_elements.append($lamp_12)
	_elements.append($lamp_13)
	_elements.append($lamp_14)
	_elements.append($lamp_15)
	_elements.append($lamp_16)
	_elements.append($lamp_17)
	_elements.append($lamp_18)
	_elements.append($lamp_19)
	_elements.append($lamp_20)
	_elements.append($lamp_21)
	_elements.append($lamp_22)
	_elements.append($lamp_23)
	_elements.append($lamp_24)
	_elements.append($lamp_25)
	_elements.append($lamp_26)
	_elements.append($lamp_27)
	_elements.append($lamp_28)
	_elements.append($lamp_29)
	_elements.append($lamp_30)
	_elements.append($lamp_31)
	_elements.append($lamp_32)
	_elements.append($lamp_33)
	_elements.append($lamp_34)
	_elements.append($lamp_35)
	_elements.append($lamp_36)
